version: '3'
services:
  miner:
    build: .
    image: ssh-p2p
    container_name: miner
    privileged: true
    volumes: 
      - ./miner:/home/data
      - ./src:/home/code
    command: /sbin/init
  peer_node_1:
    build: .
    image: ssh-p2p
    container_name: peer_node_1
    privileged: true
    volumes: 
      - ./peer_node_1:/home/data
      - ./src:/home/code
    command: /sbin/init
  peer_node_2:
    build: .
    image: ssh-p2p
    container_name: peer_node_2
    privileged: true
    volumes: 
      - ./peer_node_2:/home/data
      - ./src:/home/code
    command: /sbin/init
networks:
  default:
    external:
      name: test-network